sudo: false
cache: pip
language: python
python:
  - "3.7"
services:
  - mongodb
before_install: 
  - openssl aes-256-cbc -K $encrypted_383bc2ea2d21_key -iv $encrypted_383bc2ea2d21_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - openssl aes-256-cbc -K $encrypted_170c7267c513_key -iv $encrypted_170c7267c513_iv -in ./config/cons_dev.py.enc -out ./config/cons_dev.py -d
  - openssl aes-256-cbc -K $encrypted_835283af109b_key -iv $encrypted_835283af109b_iv -in ./config/cons_prod.py.enc -out ./config/cons_prod.py -d
  - chmod 600 ~/.ssh/id_rsa
install:
  - pip install tushare pymongo loguru pytest redis
before_script:
  - sleep 15
  - mongo stock --eval 'db.createCollection("hisprice");'
  - sudo redis-server /etc/redis/redis.conf
script: pytest
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR $deploy_user@39.107.119.46:$DEPLOY_PATH
  on:
    branch: master
after_deploy:
  - ssh $deploy_user@39.107.119.46 "chmod +x $DEPLOY_PATH/my-fintech-idc/cron/*.sh"
addons:
  ssh_known_hosts: 39.107.119.46
