sudo: false
cache: pip
language: python
python:
  - "3.7"
services:
  - mongodb
env:
  global:
    - DEPS_DIR=$TRAVIS_BUILD_DIR/dependencies
  matrix:
    - WITH_TA_LIBRARY=yes
      TA_INCLUDE_PATH=$DEPS_DIR/include
      LD_LIBRARY_PATH=$DEPS_DIR/lib
      TA_LIBRARY_PATH=$DEPS_DIR/lib
before_install:
  - openssl aes-256-cbc -K $encrypted_383bc2ea2d21_key -iv $encrypted_383bc2ea2d21_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - openssl aes-256-cbc -K $encrypted_170c7267c513_key -iv $encrypted_170c7267c513_iv -in ./config/cons_dev.py.enc -out ./config/cons_dev.py -d
  - openssl aes-256-cbc -K $encrypted_835283af109b_key -iv $encrypted_835283af109b_iv -in ./config/cons_prod.py.enc -out ./config/cons_prod.py -d
  - chmod 600 ~/.ssh/id_rsa
install:
  - if [ $WITH_TA_LIBRARY = "yes" ]; then
    chmod +x build_talib_from_source.sh;
    ./build_talib_from_source.sh $DEPS_DIR;
    fi
  - pip install pandas tushare pymongo loguru pytest redis TA-Lib
before_script:
  - sleep 45
  - mongo stock --eval 'db.createCollection("hisprice");'
  - sudo redis-server /etc/redis/redis.conf
script: pytest
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR $deploy_user@39.107.119.46:$DEPLOY_PATH
  on:
    branch: master
after_deploy:
  - ssh $deploy_user@39.107.119.46 "chmod +x $DEPLOY_PATH/my-fintech-idc/cron/*.sh"
addons:
  ssh_known_hosts: 39.107.119.46
