sudo: false
language: python
python:
  - "3.7"
branches:
  only:
  - master
before_install: 
  - openssl aes-256-cbc -K $encrypted_383bc2ea2d21_key -iv $encrypted_383bc2ea2d21_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
install:
  - pip install -r requirements.txt
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR $deploy_user@39.107.119.46:$DEPLOY_PATH
  on:
    branch: master

after_deploy:
  - ssh $deploy_user@39.107.119.46 "sh $DEPLOY_PATH/cluster.sh"
