sudo: false
cache: pip
language: python
python:
  - "3.7"
on:
  branch: master
services:
  - mongodb
  - elasticsearch
env:
  global:
    - DEPS_DIR=$TRAVIS_BUILD_DIR/dependencies
  matrix:
    - WITH_TA_LIBRARY=yes
      TA_INCLUDE_PATH=$DEPS_DIR/include
      LD_LIBRARY_PATH=$DEPS_DIR/lib
      TA_LIBRARY_PATH=$DEPS_DIR/lib
before_install:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out ~/.ssh/deploy_rsa -d
  - openssl aes-256-cbc -K $encrypted_7bc3c4f9af54_key -iv $encrypted_7bc3c4f9af54_iv -in ./config/cons_dev.py.enc -out ./config/cons_dev.py -d
  - openssl aes-256-cbc -K $encrypted_85f60e4369bf_key -iv $encrypted_85f60e4369bf_iv -in ./config/cons_prod.py.enc -out ./config/cons_prod.py -d
  - chmod 600 ~/.ssh/deploy_rsa
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.8.7.deb && sudo dpkg -i --force-confnew elasticsearch-6.8.7.deb && sudo service elasticsearch restart
install:
  - if [ $WITH_TA_LIBRARY = "yes" ]; then
    chmod +x build_talib_from_source.sh;
    ./build_talib_from_source.sh $DEPS_DIR;
    fi
  - pip install -r requirements.txt
before_script:
  - sleep 20
  - mongo stock --eval 'db.createCollection("hisprice");'
  - sudo redis-server /etc/redis/redis.conf
script: pytest
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR $deploy_user@39.107.119.46:$DEPLOY_PATH
  on:
    branch: master
after_deploy:
  - ssh $deploy_user@39.107.119.46 "chmod +x $DEPLOY_PATH/my-fintech-idc/cron/*.sh"
addons:
  ssh_known_hosts: 39.107.119.46
